export const AUTH_REDIRECT = 'AUTH_REDIRECT';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

export const AUTH_VERIFY_REQUEST = 'AUTH_VERIFY_REQUEST';
export const AUTH_VERIFY_SUCCESS = 'AUTH_VERIFY_SUCCESS';
export const AUTH_VERIFY_FAILURE = 'AUTH_VERIFY_FAILURE';
